version: 2

defaults: &defaults
  docker:
    - image: circleci/node:12
  working_directory: ~/blog

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run: npm install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run: npm run test --no-cache

  deploy-gh:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run: git config user.email "kemalpiro@gmail.com"
      - run: git config user.name "CircleCI"
      - run: npm run deploy

workflows:
  version: 2
  test:
    jobs:
      - install:
          filters:
            branches:
              ignore:
                - gh-pages
                - master
      - test:
          requires:
            - install

  deploy:
    jobs:
      - install:
          filters:
            branches:
              only:
                - master
      - test:
          requires:
            - install
      - deploy-gh:
          requires:
            - test
            - install
